### ISSUE TITLE
click server haproxy config edit report error

### ISSUE THREAD

**Issue by wangjunking** [Aidaho12/haproxy-wi#125]
![p1](https://user-images.githubusercontent.com/41409477/61273876-1eed7400-a7dd-11e9-8c1b-f2f42bde1c56.png)

click edit,report an error
![p2](https://user-images.githubusercontent.com/41409477/61274060-84d9fb80-a7dd-11e9-8926-31a6736d1623.png)

[Tue Jul 16 15:20:14.557658 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: self.curve, Q_S_bytes, referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.557840 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: /usr/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding., referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.557877 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: hm.add_string(self.Q_C.public_numbers().encode_point()), referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.557906 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: Traceback (most recent call last):, referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.557947 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: File "/var/www/haproxy-wi/app/config.py", line 48, in <module>, referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.557968 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: config_read = conf.read(), referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.558010 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode, referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.558045 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: return codecs.ascii_decode(input, self.errors)[0], referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.558107 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] AH01215: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2308: ordinal not in range(128), referer: http://10.222.11.56:8080/app/config.py
[Tue Jul 16 15:20:14.580006 2019] [cgi:error] [pid 26635] [client 10.171.23.14:60480] End of script output before headers: config.py, referer: http://10.222.11.56:8080/app/config.py

pls ,help me.thanks!

**Comment by Aidaho12** [comment]
Don't use not UTF codec in your haproxy configs

**Comment by wangjunking** [comment]
OK,THANKS.
