### ISSUE TITLE
Can't start metrics master, so no metrics

### ISSUE THREAD

**Issue by Ssshafi** [Aidaho12/haproxy-wi#160]
Hello,
First of all, thanks for this, it's a great piece of software.
I try to get metrics working for my Haproxy & Haproxy-wi  but I'm stuck.
I'm on centos 7, Haproxy 2.0.7 and Haproxy-wi 3.5.7.1 git (sqlite local).
I copied metrics_haproxy.service from /var/www/haproxy-wi/config_other/systemd to systemd folder, made a reload, enable but the service doesn't start. (keep_alive and checker are ok)

Errors in metrics-error.log :
```
Oct 23 14:08:23 haproxy metrics: Traceback (most recent call last):
Oct 23 14:08:23 haproxy metrics: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 112, in <module>
Oct 23 14:08:23 haproxy metrics: main()
Oct 23 14:08:23 haproxy metrics: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 42, in main
Oct 23 14:08:23 haproxy metrics: waf_servers = sql.select_waf_servers()
Oct 23 14:08:23 haproxy metrics: TypeError: select_waf_servers() missing 1 required positional argument: 'serv'
```

Errors in error.log :
```
[Wed Oct 23 13:53:01.617878 2019] [cgi:error] [pid 1454] [client 66.249.69.224:36665] AH01215: Traceback (most recent call last):
[Wed Oct 23 13:53:01.617950 2019] [cgi:error] [pid 1454] [client 66.249.69.224:36665] AH01215: File "/var/www/haproxy-wi/app/overview.py", line 40, in <module>
[Wed Oct 23 13:53:01.617983 2019] [cgi:error] [pid 1454] [client 66.249.69.224:36665] AH01215: role = sql.get_user_role_by_uuid(user_id.value),
[Wed Oct 23 13:53:01.618019 2019] [cgi:error] [pid 1454] [client 66.249.69.224:36665] AH01215: AttributeError: 'NoneType' object has no attribute 'value'
[Wed Oct 23 14:09:14.752885 2019] [cgi:error] [pid 1437] [client 172.16.17.2:53512] AH01215: Traceback (most recent call last):, referer: https://172.18.9.4/app/metrics.py
[Wed Oct 23 14:09:14.752971 2019] [cgi:error] [pid 1437] [client 172.16.17.2:53512] AH01215: File "/var/www/haproxy-wi/app/options.py", line 696, in <module>, referer: https://172.18.9.4/app/metrics.py
[Wed Oct 23 14:09:14.752999 2019] [cgi:error] [pid 1437] [client 172.16.17.2:53512] AH01215: metrics['chartData']['server'] = server, referer: https://172.18.9.4/app/metrics.py
[Wed Oct 23 14:09:14.753024 2019] [cgi:error] [pid 1437] [client 172.16.17.2:53512] AH01215: NameError: name 'server' is not defined, referer: https://172.18.9.4/app/metrics.py
```

Could you please help me ?

**Comment by Aidaho12** [comment]
Hi, thank you )

Have you enabled metrics at the admin page?

**Comment by Ssshafi** [comment]
In AdminsArea > Servers > MyHaproxy , yes it is check.

**Comment by Aidaho12** [comment]
Can you do:
```
select * from metrics limit 10;
```
?

**Comment by Ssshafi** [comment]
No records :
```
[root@haproxy app]# sqlite3 haproxy-wi.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> select * from metrics limit 10;
sqlite>
```

**Comment by Aidaho12** [comment]
Ok, I think I found bug. You may edit file app/tools/metrics_master.py:
```
try:
        waf_servers = sql.select_waf_servers()
	waf_started_workers = get_waf_worker()
	waf_servers_list = []
			
	for serv in waf_servers:
		waf_servers_list.append(serv[0])
except:
        pass
```

Or wait while I release bug fix

**Comment by Ssshafi** [comment]
I need to put un little bit more in the "try" to get it work :
```
        if need_start:
                for serv in need_start:
                        start_worker(serv)
        try:
                waf_servers = sql.select_waf_servers()
                waf_started_workers = get_waf_worker()
                waf_servers_list = []

                for serv in waf_servers:
                        waf_servers_list.append(serv[0])

                waf_need_kill=list(set(waf_started_workers) - set(waf_servers_list))
                waf_need_start=list(set(waf_servers_list) - set(waf_started_workers))

                if waf_need_kill:
                        for serv in waf_need_kill:
                                kill_waf_worker(serv)

                if waf_need_start:
                        for serv in waf_need_start:
                                start_waf_worker(serv)
        except:
                pass
```
Now metrics master and workers are green in overview and I can see stats and graph in metrics.

Thanks a lot

**Comment by Aidaho12** [comment]
You are welcome :)

**Comment by Ravan18** [comment]
![service](https://user-images.githubusercontent.com/58604104/70819316-864d3580-1e08-11ea-8511-4b13931979b6.JPG)
I can't start both services

**Comment by Aidaho12** [comment]
It's sad :(

**Comment by Ravan18** [comment]
Could you give me some advice psl

**Comment by Aidaho12** [comment]
Check logs

**Comment by Ravan18** [comment]
Could you remote to check, it's possible ?

**Comment by Aidaho12** [comment]
Yes, it's possible, but doesn't free

**Comment by Ravan18** [comment]
I can donate for you, if it qualify with my requirement.

**Comment by Ravan18** [comment]
Can I have your skype or telegram?

**Comment by Aidaho12** [comment]
I have, there are list: https://haproxy-wi.org/contacts.py
