### ISSUE TITLE
Error installing on RPi

### ISSUE THREAD

**Issue by Tirpitz93** [Aidaho12/haproxy-wi#24]
bytes/string conversion issue. seams to be Py3k compatibility issue.

```
Downloading/unpacking dump==0.0.3 (from -r /var/www/haproxy-wi/requirements.txt (line 7))
  Downloading dump-0.0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-uasclc1x/dump/setup.py) egg_info for package dump
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-uasclc1x/dump/setup.py", line 13, in <module>
        version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)
      File "/usr/lib/python3.4/re.py", line 166, in search
        return _compile(pattern, flags).search(string)
    TypeError: can't use a string pattern on a bytes-like object
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-uasclc1x/dump/setup.py", line 13, in <module>

    version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)

  File "/usr/lib/python3.4/re.py", line 166, in search

    return _compile(pattern, flags).search(string)

TypeError: can't use a string pattern on a bytes-like object

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-uasclc1x/dump
Storing debug log for failure in /root/.pip/pip.log
Unable to install Required Packages, Please check Pip error log and Fix the errors and Rerun the script

```

**Comment by Tirpitz93** [comment]
oops wrong, project, meant to post to lib project

**Comment by Aidaho12** [comment]
OK )

**Comment by Tirpitz93** [comment]
unless of course you have a working workaround?

**Comment by Aidaho12** [comment]
Yes, you first had this problem :(

**Comment by Tirpitz93** [comment]
I will test fully when I get home from work. it installed without via ssh though.

**Comment by Tirpitz93** [comment]
will test later when I am on the same network again.

**Comment by ichbestimmtnicht** [comment]
Just installed it on RPi3b (dietpi up-to-date) and I did not encountered this issue.
