### ISSUE TITLE
Admin Area blank pages

### ISSUE THREAD

**Issue by spokky** [Aidaho12/haproxy-wi#252]
Hi as someone else I've just installed on a Ubuntu 20. Everything works fine expect for the admin area.  This is the only thing that appears in error log:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/users.py", line 70, in <module>
    openvpn=openvpn[0],
NameError: name 'openvpn' is not defined
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/users.py", line 70, in <module>
    openvpn=openvpn[0],
NameError: name 'openvpn' is not defined
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/users.py", line 70, in <module>
    openvpn=openvpn[0],
NameError: name 'openvpn' is not defined

**Comment by Aidaho12** [comment]
Hi

update users.py file in app folder. It should work now
