### ISSUE TITLE
rpm package fresh install klick on "add proxy" -> empty white site

### ISSUE THREAD

**Issue by n1ete** [Aidaho12/haproxy-wi#258]
Everything stated in headline already, 
This happens with the rpm repo on fresh updated centos 8.

These are the corresponding http error logs when this happens:

```
[Wed Jan 06 04:04:31.780008 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138] Traceback (most recent call last):: /var/www/haproxy-wi/app/add.py
[Wed Jan 06 04:04:31.780116 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138]   File "/var/www/haproxy-wi/app/add.py", line 35, in <module>: /var/www/haproxy-wi/app/add.py
[Wed Jan 06 04:04:31.780153 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138]     os.makedirs(dir): /var/www/haproxy-wi/app/add.py
[Wed Jan 06 04:04:31.780214 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138]   File "/usr/lib64/python3.6/os.py", line 220, in makedirs: /var/www/haproxy-wi/app/add.py
[Wed Jan 06 04:04:31.780240 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138]     mkdir(name, mode): /var/www/haproxy-wi/app/add.py
[Wed Jan 06 04:04:31.780320 2021] [cgid:error] [pid 1538:tid 140590964524800] [client 100.64.4.2:49138] FileExistsError: [Errno 17] File exists: '/var/www/haproxy-wi/lists': /var/www/haproxy-wi/app/add.py
```

thanks for your help

**Comment by Aidaho12** [comment]
What version have you installed?

**Comment by n1ete** [comment]
I still got access to the repo, so it should be the latest

**Comment by Aidaho12** [comment]
Please look at version, if it not 4.5.7 update среда, 06 января 2021г., 18:23 +06:00 от jcccb  notifications@github.com :

**Comment by n1ete** [comment]
you where right, an simple 'yum update haproxy-wi' fixed it. i am used to think if i do a fresh install on an fresh updated os, that i am on the latestet version. that wasnt the case 👍
