### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by HectorHumanes** [Aidaho12/haproxy-wi#55]
I've tested the docker image you provide, but I'm getting a 500 error when I try to access to the dashboard. Logs show me this error:
```
[Thu Oct 04 13:06:16.844449 2018] [cgi:error] [pid 8] [client 172.21.0.1:49426] AH01215: Traceback (most recent call last):
[Thu Oct 04 13:06:16.844577 2018] [cgi:error] [pid 8] [client 172.21.0.1:49426] AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 5, in <module>
[Thu Oct 04 13:06:16.844616 2018] [cgi:error] [pid 8] [client 172.21.0.1:49426] AH01215:     from jinja2 import Environment, FileSystemLoader
[Thu Oct 04 13:06:16.844644 2018] [cgi:error] [pid 8] [client 172.21.0.1:49426] AH01215: ImportError: No module named 'jinja2'
[Thu Oct 04 13:06:16.854635 2018] [cgi:error] [pid 8] [client 172.21.0.1:49426] End of script output before headers: overview.py
[Thu Oct 04 13:06:19.183105 2018] [cgi:error] [pid 11] [client 172.21.0.1:49444] AH01215: Traceback (most recent call last):
[Thu Oct 04 13:06:19.183207 2018] [cgi:error] [pid 11] [client 172.21.0.1:49444] AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 5, in <module>
[Thu Oct 04 13:06:19.183245 2018] [cgi:error] [pid 11] [client 172.21.0.1:49444] AH01215:     from jinja2 import Environment, FileSystemLoader
[Thu Oct 04 13:06:19.183274 2018] [cgi:error] [pid 11] [client 172.21.0.1:49444] AH01215: ImportError: No module named 'jinja2'
[Thu Oct 04 13:06:19.192467 2018] [cgi:error] [pid 11] [client 172.21.0.1:49444] End of script output before headers: overview.py
[Thu Oct 04 13:10:35.927703 2018] [cgi:error] [pid 9] [client 172.21.0.1:50475] AH01215: Traceback (most recent call last):
[Thu Oct 04 13:10:35.927809 2018] [cgi:error] [pid 9] [client 172.21.0.1:50475] AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 5, in <module>
[Thu Oct 04 13:10:35.927847 2018] [cgi:error] [pid 9] [client 172.21.0.1:50475] AH01215:     from jinja2 import Environment, FileSystemLoader
[Thu Oct 04 13:10:35.927875 2018] [cgi:error] [pid 9] [client 172.21.0.1:50475] AH01215: ImportError: No module named 'jinja2'
[Thu Oct 04 13:10:35.936754 2018] [cgi:error] [pid 9] [client 172.21.0.1:50475] End of script output before headers: overview.py
```
¿Maybe you forgot to add jinja2 library tothe docker image?

Thanks!

**Comment by Aidaho12** [comment]
yes it seems, will fix
--
Отправлено из Mail.Ru для Android четверг, 04 октября 2018г., 19:30 +06:00 от Humanes  notifications@github.com :

**Comment by HectorHumanes** [comment]
Thanks! :)

**Comment by Aidaho12** [comment]
Fixed, try )

**Comment by HectorHumanes** [comment]
Now it's working perfectly!

Thanks for your quickness ;)

**Comment by Aidaho12** [comment]
Welcome)

leave a review after you try, well, put likes, subscribe;)
