### ISSUE TITLE
Metrics not displayed 

### ISSUE THREAD

**Issue by akihirok2k2** [Aidaho12/haproxy-wi#76]
Hi. 
When I access "http:/MyServer:8080/app/metrics.py" on a browser, the following screen appears

![image](https://user-images.githubusercontent.com/20021909/48121497-77688b00-e2b8-11e8-856f-0cfd7511eb75.png)

Using
  OS : CentOS Linux release 7.4.1708 (Core)
  DB : mariadb-5.5.60-1

Data was contained in table of DB
```
MariaDB [haproxywi]> select * from metrics;
+--------------+----------+-------------+-----------+---------------+---------------------+
| serv         | curr_con | cur_ssl_con | sess_rate | max_sess_rate | date                |
+--------------+----------+-------------+-----------+---------------+---------------------+
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:02:33 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:02:43 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:02:53 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:03:03 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:03:13 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:03:23 |
| 127.0.0.1    |        0 |           0 |         0 |             1 | 2018-11-06 17:03:33 |
```

Commenting out "table_stat = sql.select_table_metrics (user_id.value)" resulted in the following screen.
![image](https://user-images.githubusercontent.com/20021909/48122602-4e95c500-e2bb-11e8-8e31-c51e3ed8cd27.png)

I'm sorry...  please tell me What should I do?

**Comment by Aidaho12** [comment]
In httpd error log something have?
--
Отправлено из Mail.Ru для Android среда, 07 ноября 2018г., 15:35 +06:00 от あきひろ  notifications@github.com :

**Comment by akihirok2k2** [comment]
Sorry for my late reply.
logging in haproxy-wi.error.log......  I am sorry that I could not confirm it before this issuee.  orz

In /var/log/httpd/haproxy-wi.access.log
```
<MY-HOME-IP> - - [08/Nov/2018:09:40:16 +0900] "GET /app/metrics.py HTTP/1.1" 200 - "http://<MY-WEB-IP>:8080/app/viewsttats.py?serv=127.0.0.1" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
```

In /var/log/httpd/haproxy-wi.error.log
```
[Thu Nov 08 09:39:03.410871 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: Traceback (most recent call last):
[Thu Nov 08 09:39:03.410945 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/usr/lib64/python3.5/site-packages/mysql/connector/connection_cext.py", line 377, in cmd_query
[Thu Nov 08 09:39:03.410976 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     raw_as_string=raw_as_string)
[Thu Nov 08 09:39:03.411011 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: _mysql_connector.MySQLInterfaceError: Unknown column 'avg_cur_3d' in 'field list'
[Thu Nov 08 09:39:03.411013 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:
[Thu Nov 08 09:39:03.411042 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: During handling of the above exception, another exception occurred:
[Thu Nov 08 09:39:03.411045 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:
[Thu Nov 08 09:39:03.411060 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: Traceback (most recent call last):
[Thu Nov 08 09:39:03.411093 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/var/www/haproxy-wi/app/sql.py", line 1024, in select_table_metrics
[Thu Nov 08 09:39:03.411103 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     cur.execute(sql)
[Thu Nov 08 09:39:03.411144 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/usr/lib64/python3.5/site-packages/mysql/connector/cursor_cext.py", line 264, in execute
[Thu Nov 08 09:39:03.411162 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     raw_as_string=self._raw_as_string)
[Thu Nov 08 09:39:03.411205 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/usr/lib64/python3.5/site-packages/mysql/connector/connection_cext.py", line 380, in cmd_query
[Thu Nov 08 09:39:03.411218 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     sqlstate=exc.sqlstate)
[Thu Nov 08 09:39:03.411260 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'avg_cur_3d' in 'field list'
[Thu Nov 08 09:39:03.411262 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:
[Thu Nov 08 09:39:03.411291 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: During handling of the above exception, another exception occurred:
[Thu Nov 08 09:39:03.411293 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:
[Thu Nov 08 09:39:03.411309 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: Traceback (most recent call last):
[Thu Nov 08 09:39:03.411337 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/var/www/haproxy-wi/app/metrics.py", line 28, in <module>
[Thu Nov 08 09:39:03.411363 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     table_stat = sql.select_table_metrics(user_id.value),
[Thu Nov 08 09:39:03.411395 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/var/www/haproxy-wi/app/sql.py", line 1026, in select_table_metrics
[Thu Nov 08 09:39:03.411404 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     out_error(e)
[Thu Nov 08 09:39:03.411431 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:   File "/var/www/haproxy-wi/app/sql.py", line 21, in out_error
[Thu Nov 08 09:39:03.411509 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215:     print('<span class="alert alert-danger" id="error">An error occurred: ' + error + ' <a title="Close" id="errorMess"><b>X</b></a></span>')
[Thu Nov 08 09:39:03.411541 2018] [cgi:error] [pid 1326] [client <MY-HOME-IP>:11292] AH01215: TypeError: Can't convert 'ProgrammingError' object to str implicitly
```

**Comment by Aidaho12** [comment]
Update and try again

**Comment by akihirok2k2** [comment]
Ohhhh!!!!!! Tnaks your help.
I could see "Metrics" view  !!!!

**Comment by Aidaho12** [comment]
Welcome )
If you want, you can donate and support project ;)
